export const AUTH_LOADING = "AUTH_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const USER_LOAD_ERROR = "USER_LOAD_ERROR";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
